swagger: '2.0'
info:
  version: v1
  title: My API
paths:
  /Servak/api/comics:
    get:
      tags:
        - Servak
      operationId: ComicsGetAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: object
  '/Servak/api/comics/id/{id}':
    get:
      tags:
        - Servak
      operationId: ComicsGetById
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: object
definitions: {}