swagger: '2.0'
info:
  version: v1
  title: My API
host: gcpd-294815.appspot.com
paths:
  /LaborExchange/api/comics:
    get:
      tags:
        - LaborExchange
      operationId: ComicsGetAll
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: object
  '/LaborExchange/api/comics/id/{id}':
    get:
      tags:
        - LaborExchange
      operationId: ComicsGetById
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: object
  '/LaborExchange/api/comics/page/{page}/pagecount/{pagecount}':
    get:
      tags:
        - LaborExchange
      operationId: ComicsGetByPageAndPagecount
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: page
          in: path
          required: true
          type: integer
          format: int32
        - name: pagecount
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: object
definitions: {}
